### ISSUE TITLE
Incorrect case for FizzBuzz, Fizz and Buzz.

### ISSUE THREAD

**Issue by barberboy** [Moser2010/webtech#10]
You should be logging "[FizzBuzz](https://github.com/Moser2010/webtech/blob/master/fizzbuzz.js#L6)", "[Fizz](https://github.com/Moser2010/webtech/blob/master/fizzbuzz.js#L9)", and "[Buzz](https://github.com/Moser2010/webtech/blob/master/fizzbuzz.js#L12)".

**Comment by Moser2010** [comment]
I'm not sure what you mean cause when I run the program it shows all those and the numbers. Do you have an example of what its suppose to look like?

**Comment by barberboy** [comment]
You are logging "FIZZBUZZ", "FIZZ", and "BUZZ". You should be logging "FizzBuzz", "Fizz", and "Buzz".

**Comment by Moser2010** [comment]
Okay I see what you mean. My bad. Okay I did that. Anything else?

**Comment by barberboy** [comment]
Nope, that was the last issue! :100:
