### ISSUE TITLE
Clean up unnecessary comments

### ISSUE THREAD

**Issue by barberboy** [Moser2010/webtech#8]
The code currently contains a lot of superfluous and messy comments. They should be cleaned up and/or removed.
- [x] The comments from the assignment specification should (ideally) be removed or better organized. If you keep them, at least do the following:
  - [x] replace the tab character with regular spaces
  - [x] wrap the lines at 80 characters
  - [x] include them in a single comment block at the top of the file as a numbered list, and refer to the numbers with inline comments, like `// [1]` or something similar
- [x] The commented-out test code should be removed or moved into a different file. If you're using git, you don't have to worry about losing old code, since you can always [review old commits](https://github.com/Moser2010/webtech/commits/master)

**Comment by Moser2010** [comment]
I was wondering why Tabs should be replaced with spaces. I also don't know how to wrap lines. Can you tell me how you do that.

**Comment by barberboy** [comment]
To wrap, use a multi-line comment block instead of single line, and hit enter when you want to go to a new line.

Spaces should be used instead of tabs because this looks like garbage:

![screen shot 2015-09-01 at 11 04 01 pm](https://cloud.githubusercontent.com/assets/371332/9622809/deb56a08-50fd-11e5-99b9-75f3516dfaeb.png)

**Comment by barberboy** [comment]
:+1:
